apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-ad-statistics-frontend
  namespace: default
  labels:
    team: easymoneysnipers
spec:
  image: {{ image }}
  port: 9000
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    initialDelay: 60
    path: /internal/isAlive
  readiness:
    initialDelay: 60
    path: /internal/isReady
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  vault:
    enabled: false
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}